name: FunWithRunners
# some cool commment

on:
  workflow_dispatch:
    inputs:
      runner:
        description: set your pool
        type: string
        default: None

jobs:
  run-allocated-runner:
    runs-on: [self-hosted, "1ES.Pool=${{ inputs.runner }}"]
    steps:
      - name: Run a task
        run: | 
          echo "Hello there!!!"
          echo $hostname