name: FunWithRunners
# some cool commment

on:
  workflow_dispatch:
    inputs:
      runner:
        description: Choose a runner
        required: true
        type: choice
        options:
          - windows
          - linux
          - macos

jobs:
  allocate-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Allocate a runner
        id: runner_allocation
        run: |
          if [[ ${{ inputs.runner }} = 'linux' ]];
          then
            echo "runner=${{ secrets.LINUX_AGENT }}" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.runner }} = 'windows' ]];
          then
            echo "runner=windows-2019" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.runner }} = 'macos' ]];
          then
            echo "runner='macos-10.15'" >> $GITHUB_OUTPUT
          fi

    outputs:
      chosenRunner: ${{ steps.runner_allocation.outputs.runner }}
  
  run-allocated-runner:
    needs: allocate-runner
    runs-on: ${{ needs.allocate-runner.outputs.chosenRunner }}
    steps:
      - name: Run a task
        run: | 
          echo "Hello there!!!"
          echo $hostname