name: FunWithRunners
# some cool commment

on:
  workflow_dispatch:
    inputs:
      runner:
        description: set your pool
        type: string
        default: None

jobs:
  # allocate-runner:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Allocate a runner
  #       id: runner_allocation
  #       run: |
  #         if [[ ${{ inputs.runner }} = 'ubuntu-latest' ]];
  #         then
  #           echo "runner=Agent" >> $GITHUB_OUTPUT
  #         fi
  #         if [[ ${{ inputs.runner }} = 'windows' ]];
  #         then
  #           echo "runner=windows-2019" >> $GITHUB_OUTPUT
  #         fi
  #         if [[ ${{ inputs.runner }} = 'macos' ]];
  #         then
  #           echo "runner='macos-10.15'" >> $GITHUB_OUTPUT
  #         fi

  #   outputs:
  #     chosenRunner: ${{ steps.runner_allocation.outputs.runner }}
  
  run-allocated-runner:
    # needs: allocate-runner
    runs-on: [self-hosted, "${{ inputs.runner }}"]
    steps:
      - name: Run a task
        run: | 
          echo "Hello there!!!"
          echo $hostname

  # run-allocate-runner-deux:
  #   needs: allocate-runner
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run a task
  #       run: | 
  #         echo "Hello there!!!"
  #         echo ${{ needs.allocate-runner.outputs.chosenRunner }}